# Generated by Django 4.2.8 on 2024-01-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_featured_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_product',
            name='image',
            field=models.ImageField(upload_to='images/featured'),
        ),
    ]
